#!/usr/bin/python3

import argparse

OoTAsciiCharacterMap = {
    "À": 0x80,
    "î": 0x81,
    "Â": 0x82,
    "Ä": 0x83,
    "Ç": 0x84,
    "È": 0x85,
    "É": 0x86,
    "Ê": 0x87,
    "Ë": 0x88,
    "Ï": 0x89,
    "Ô": 0x8A,
    "Ö": 0x8B,
    "Ù": 0x8C,
    "Û": 0x8D,
    "Ü": 0x8E,
    "ß": 0x8F,
    "à": 0x90,
    "á": 0x91,
    "â": 0x92,
    "ä": 0x93,
    "ç": 0x94,
    "è": 0x95,
    "é": 0x96,
    "ê": 0x97,
    "ë": 0x98,
    "ï": 0x99,
    "ô": 0x9A,
    "ö": 0x9B,
    "ù": 0x9C,
    "û": 0x9D,
    "ü": 0x9E,
}

def recodeMsg(filepath: str) -> str:
    with open(filepath) as f:
        contents = f.read()

    warningNotice = "// This is an autogenerated file.\n// Any change made to this file will be overwritten in next compilation.\n"

    contents = warningNotice + contents

    for char, hexVal in OoTAsciiCharacterMap.items():
        escapedValue = '" "\\x' + hex(hexVal)[2:] + '" "'
        contents = contents.replace(char, escapedValue)

    return contents


def main():
    description = ""

    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("filepath", help="Message C file to process.")
    args = parser.parse_args()

    print(recodeMsg(args.filepath))

if __name__ == "__main__":
    main()
